{% set name = "jupyterlab-vega2" %}
{% set version = "3.2.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/jupyterlab-vega2-{{ version }}.tar.gz
  sha256: b96a6bd75c74c1ffbfef499d127b1b23ea7e8c0a2d58355eebd71dd474ca8a17

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - jupyter-packaging >=0.7.9,<0.8.0
    - pip
    - python >=3.6
  run:
    - jupyterlab ~=3.0
    - python >=3.6

test:
  commands:
    - pip check
    - test -f "${PREFIX}/share/jupyter/labextensions/@jupyterlab/vega2-extension/package.json"                                    # [unix]
    - if exist %PREFIX%\\share\\jupyter\\labextensions\\@jupyterlab\\vega2-extension\\package.json (exit 0) else (exit 1)         # [win]
  requires:
    - pip

about:
  home: https://github.com/jupyterlab/jupyter-renderers
  summary: JupyterLab - Vega 2 and Vega-Lite 1 Mime Renderer Extension
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jtpio
    - jasongrout
    - blink1073
